name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Flood and Fuzz contracts'  

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Log level: ${{ github.event.inputs.logLevel }}"
            echo "Tags: ${{ github.event.inputs.tags }}" 
            
            
  ddos:
    name: flood and fuzz contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run flood
  
